### PRODUCTS STOCK END-POINTS

### all products stock query proccess
GET http://localhost:3000/products-stock HTTP/1.1


### active product for id query proccess
GET http://localhost:3000/products-stock-id/7 HTTP/1.1
