### PURCHASE ORDERS END-POINTS

### all purchase orders query proccess
GET http://localhost:3000/purchase-orders HTTP/1.1


### all open purchase orders query proccess
GET http://localhost:3000/purchase-orders-status/open HTTP/1.1


### all canceled purchase orders query proccess
GET http://localhost:3000/purchase-orders-status/canceled HTTP/1.1


### all received purchase orders query proccess
GET http://localhost:3000/purchase-orders-status/received HTTP/1.1


### purchase orders data query proccess
GET http://localhost:3000/purchase-orders-data/12 HTTP/1.1


### purchase orders record
POST http://localhost:3000/purchase-orders HTTP/1.1
Content-Type: application/json

{
    "provider": "Kara Coatings Filial 1"
    , "status": "active"
    , "total": 11200.50
    , "items": [
        {
            "product_id": 1
            , "status": "active"
            , "unit": "m2"
            , "unit_price": 21.45
            , "amount": 250.00
            , "total": 5362.50
        }
        , {
            "product_id": 7
            , "status": "active"
            , "unit": "m2"
            , "unit_price": 48.65
            , "amount": 120.00
            , "total": 5838.00
        }
    ]
}

### purchase orders update
PUT http://localhost:3000/purchase-orders/16 HTTP/1.1
Content-Type: application/json

{
    "provider": "Kara Coatings Filial 1"
    , "status": "open"
    , "total": 11200.50
    , "items": [
        {
            "product_id": 1
            , "status": "active"
            , "unit": "m2"
            , "unit_price": 21.45
            , "amount": 250.00
            , "total": 5362.50
        }
        , {
            "product_id": 7
            , "status": "active"
            , "unit": "m2"
            , "unit_price": 48.65
            , "amount": 120.00
            , "total": 5838.00
        }
    ]
}


### purchase orders closing
PUT http://localhost:3000/purchase-orders-closing/18 HTTP/1.1
Content-Type: application/json


### purchase orders receiving
PUT http://localhost:3000/purchase-orders-receiving/18 HTTP/1.1
Content-Type: application/json